apiVersion: v1
kind: ConfigMap
metadata:
  name: ums-config
  namespace: ums
data:
  Seq__ServerUrl: "http://seq:5341"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"
  ConnectionStrings__kafka: "kafka:9092"
  Auth__Authority: "http://identity-api:8080"
  Auth__Audience: "api-gateway"
  Auth__RequireHttpsMetadata: "false"
  UMS__SeedTenantSlug: "ums"
  ASPNETCORE_ENVIRONMENT: "Production"
  ConnectionStrings__AcademicDb: "Host=postgres-0.postgres;Port=5432;Database=AcademicDb;Username=postgres;Password=postgres"
  ConnectionStrings__AttendanceDb: "Host=postgres-0.postgres;Port=5432;Database=AttendanceDb;Username=postgres;Password=postgres"
  ConnectionStrings__ExaminationDb: "Host=postgres-0.postgres;Port=5432;Database=ExaminationDb;Username=postgres;Password=postgres"
  ConnectionStrings__FacultyDb: "Host=postgres-0.postgres;Port=5432;Database=FacultyDb;Username=postgres;Password=postgres"
  ConnectionStrings__FeeDb: "Host=postgres-0.postgres;Port=5432;Database=FeeDb;Username=postgres;Password=postgres"
  ConnectionStrings__HostelDb: "Host=postgres-0.postgres;Port=5432;Database=HostelDb;Username=postgres;Password=postgres"
  ConnectionStrings__IdentityDb: "Host=postgres-0.postgres;Port=5432;Database=IdentityDb;Username=postgres;Password=postgres"
  ConnectionStrings__NotificationDb: "Host=postgres-0.postgres;Port=5432;Database=NotificationDb;Username=postgres;Password=postgres"
  ConnectionStrings__StudentDb: "Host=postgres-0.postgres;Port=5432;Database=StudentDb;Username=postgres;Password=postgres"
